<?php
include('include/connection.php');
include('include/functions.php');
unset($_SESSION['USER_LOGIN']);
unset($_SESSION['USER_ID']);
unset($_SESSION['USER_NAME']);
header('location:login.php');
die();
?>